service: bodycam-pi3
useDotenv: true
frameworkVersion: "3"

plugins:
  - serverless-python-requirements

custom:
  bucket_name: ${env:BUCKET_NAME}
  account_number: ${env:ACCOUNT_NUMBER}
  apiGateway:
    binaryMediaTypes:
      - image/jpeg
      - audio/wav
      - audio/mpeg

provider:
  profile: personal
  name: aws
  runtime: python3.12
  region: us-east-1
  timeout: 100
  memorySize: 256

  environment:
    BUCKET_NAME: ${self:custom.bucket_name}
    TRANSCRIPTS_PREFIX: transcripts/
    LANGUAGE_CODE: es-ES
    NOVA_MODEL_ARN: arn:aws:bedrock:us-east-1:339712886600:inference-profile/us.amazon.nova-lite-v1:0
    ACCOUNT_NUMBER: ${self:custom.account_number}

  iam:
    role:
      statements:
        # ────────── S3 permisos (ya tenías) ──────────
        - Effect: Allow
          Action: s3:PutObject
          Resource: arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*

        - Effect: Allow
          Action: s3:GetObject
          Resource: arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/${self:provider.environment.TRANSCRIPTS_PREFIX}*

        # ────────── Amazon Transcribe ──────────
        - Effect: Allow
          Action:
            - transcribe:StartTranscriptionJob
            - transcribe:GetTranscriptionJob
          Resource: "*"

        # ────────── Amazon Bedrock (Nova Lite) ──────────
        - Effect: Allow
          Action:
            - bedrock:InvokeModel
          Resource:
            - arn:aws:bedrock:us-east-1::foundation-model/amazon.nova-lite-v1
            - arn:aws:bedrock:us-east-1::foundation-model/amazon.nova-lite-v1:0

functions:
  uploadImage:
    handler: src/image_handler.lambda_handler
    events:
      - httpApi:
          path: /upload-image
          method: post

  uploadAudio:
    handler: src/audio_handler.lambda_handler
    events:
      - httpApi:
          path: /upload-audio
          method: post

  transcribeComplete:
    handler: src/transcribe_handler.lambda_handler
    events:
      - eventBridge:
          pattern:
            source:
              - aws.transcribe
            detail-type:
              - Transcribe Job State Change
            detail:
              TranscriptionJobStatus:
                - COMPLETED
    timeout: 120
    memorySize: 256
